name: Build

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: 'Game Package Name (e.g. com.example.game)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Zygisk-Il2CppDumper
          path: app/build/outputs/apk/release/*.apk
